### ISSUE TITLE
Clean code, Good job 👍

### ISSUE THREAD

**Issue by Abisku** [CapciGithub/Growtopia-CID-Creator#1]

**Comment by CapciGithub** [comment]
Not my code tho but still thanks to the one who released this. Just made compatible with Google Cloud Shell because why not. They can make you create unlimited accounts without worrying about VPN's.

**Comment by Abisku** [comment]
Who's the original creator?

**Comment by CapciGithub** [comment]
> Who's the original creator?

Don't know who is the original creator. Some random Indonesian guy was selling this for 5DL in youtube. I got my hands on his source code and decided to share for free because he was getting 2DLS from people everytime growtopia releases a new update. ( which is kinda bs because changing the version aint that hard he was using people who don't have knowledge) I got the source code, made compatible with Google Cloud Shell for more easy/compact usage of the code and more easy to create accounts since everytime you reset your Google Cloud Shell VM it gives you a new Ip address and it does take few seconds to do that so basically unlimited account creation.

**Comment by Abisku** [comment]
> > Who's the original creator?
> 
> Don't know who is the original creator. Some random Indonesian guy was selling this for 5DL in youtube. I got my hands on his source code and decided to share for free because he was getting 2DLS from people everytime growtopia releases a new update. ( which is kinda bs because changing the version aint that hard he was using people who don't have knowledge) I got the source code, made compatible with Google Cloud Shell for more easy/compact usage of the code and more easy to create accounts since everytime you reset your Google Cloud Shell VM it gives you a new Ip address and it does take few seconds to do that so basically unlimited account creation.


I think growtopia has some kind of ip limits when your creating accounts too fast, same with bruteforcing gt accounts. Could this work without restarting Cloud Shell if I put more delay on it or what causes the need for restart

**Comment by CapciGithub** [comment]
> > > Who's the original creator?
> > 
> > 
> > Don't know who is the original creator. Some random Indonesian guy was selling this for 5DL in youtube. I got my hands on his source code and decided to share for free because he was getting 2DLS from people everytime growtopia releases a new update. ( which is kinda bs because changing the version aint that hard he was using people who don't have knowledge) I got the source code, made compatible with Google Cloud Shell for more easy/compact usage of the code and more easy to create accounts since everytime you reset your Google Cloud Shell VM it gives you a new Ip address and it does take few seconds to do that so basically unlimited account creation.
> 
> I think growtopia has some kind of ip limits when your creating accounts too fast, same with bruteforcing gt accounts. Could this work without restarting Cloud Shell if I put more delay on it or what causes the need for restart

No, they do have limits but you can't bypass that by creating accounts slowly. There's x amount of account you can create per IP but no one can tell you the exact amount. Somedays i can create 20 account in 1 IP somedays only few.

**Comment by Abisku** [comment]
Do you have Discord account?, I have couple more questions

**Comment by Abisku** [comment]
> > > > Who's the original creator?
> > > 
> > > 
> > > Don't know who is the original creator. Some random Indonesian guy was selling this for 5DL in youtube. I got my hands on his source code and decided to share for free because he was getting 2DLS from people everytime growtopia releases a new update. ( which is kinda bs because changing the version aint that hard he was using people who don't have knowledge) I got the source code, made compatible with Google Cloud Shell for more easy/compact usage of the code and more easy to create accounts since everytime you reset your Google Cloud Shell VM it gives you a new Ip address and it does take few seconds to do that so basically unlimited account creation.
> > 
> > 
> > I think growtopia has some kind of ip limits when your creating accounts too fast, same with bruteforcing gt accounts. Could this work without restarting Cloud Shell if I put more delay on it or what causes the need for restart
> 
> No, they do have limits but you can't bypass that by creating accounts slowly. There's x amount of account you can create per IP but no one can tell you the exact amount. Somedays i can create 20 account in 1 IP somedays only few.

Do you have Discord account?, I have couple more questions
