### ISSUE TITLE
How to fix errors?

### ISSUE THREAD

**Issue by CapciGithub** [CapciGithub/Growtopia-CID-Creator#11]
Issue 1: Stuck at connected server
Fix: First of all, make sure your Username is not that long. Second of all make sure at least there is 1 capital letters 1 symbol and 1 number iin your password for example: Password1@ then make sure to put at least random email into
//Customing Gmail ( At least put a random gmail. Dont add @gmail.com )
string Gmail_acc = "testgmail";

change testgmail with anything random and make sure its not long keep it short and dont put @gmail.com into end.
If still somehow doesnt works, open the editor and delete the Growtopia-CID-Creator folder and do everything from step 1.

Issue 2: Stuck at disconnected server after creating x amount of accounts
Fix: Probably you're got account limit and you can't create more accounts. Click the button on showed image below this text and choose "Clean VM State" and click restart
Image: https://media.discordapp.net/attachments/900416037781131305/901503881534664815/Ekran_Alnts.PNG?width=357&height=494

Issue 3: Stuck at Message: 4UPDATE REQUIRED!``
Fix: Go to editor and find config.json change the old growtopia version into newest one and save the file. After that go to terminal and write this ./build*

I'll keep this page updated as long as i find new problems.

**Comment by KikiroCID** [comment]
How To Fix Random Number?

**Comment by CapciGithub** [comment]
> How To Fix Random Number?

You can't fix the random number that's how the script works.
But If it starts from 156 instead of 1 It means there's bot account with 1 on the end.
