### ISSUE TITLE
Can help?

### ISSUE THREAD

**Issue by ferlitopym** [CapciGithub/Growtopia-CID-Creator#2]
Im stuck connecting server, i do restart but same, nothing happen, how i sholved?

I use cloud shell

**Comment by IcyGT** [comment]
idk

**Comment by CapciGithub** [comment]
try update version, or refork the github again growtopia updated their port I'll update rn

**Comment by ferlitopym** [comment]
> try update version, or refork the github again growtopia updated their port I'll update rn

done fixed, i forget to add sysmbol on pass
