### ISSUE TITLE
Stuck at "Disconnected from server..."

### ISSUE THREAD

**Issue by bretyc** [CapciGithub/Growtopia-CID-Creator#3]
I follow the steps, but after i do ./createid why it always Disconnected from server... not create a new id

Pls answer

**Comment by CapciGithub** [comment]
> I follow the steps, but after i do ./createid why it always Disconnected from server... not create a new id
> 
> Pls answer

Growtopia changed their Port again. Open editor and go to CPPBot.cpp then find 
	bot1 = makeBot(user1, pass1,"213.179.209.168", 17250, vers, wn);
change 17250 to 17258

**Comment by bretyc** [comment]
Lol pantes:v

**Comment by bretyc** [comment]
Ty for Capci
