### ISSUE TITLE
why it create from random number

### ISSUE THREAD

**Issue by IcyGT** [CapciGithub/Growtopia-CID-Creator#4]
when i ./createid it create id but from random number like 15, 70, ++

![image](https://user-images.githubusercontent.com/94095755/144346448-2328ea8e-4a33-4240-acae-4bbbe9f31ae5.png)

**Comment by IcyGT** [comment]
can u help me

**Comment by CapciGithub** [comment]
> when i ./createid it create id but from random number like 15, 70, ++
> 
> ![image](https://user-images.githubusercontent.com/94095755/144346448-2328ea8e-4a33-4240-acae-4bbbe9f31ae5.png)

Most likely does that when there's account with that names created for example if 66 taken it does +1 to name

"START_ACC = START_ACC + 1;
START_GMAIL = START_GMAIL + 1;"

This is the code. First it creates account with the name you used after that it adds +1 to the name can be easily changed tho for example you can make it add a1 a2 a3 but I'm lazy to make that so.
