### ISSUE TITLE
stuck at needly update

### ISSUE THREAD

**Issue by KryyyNotStable** [CapciGithub/Growtopia-CID-Creator#6]
Message: `4UPDATE REQUIRED!`` : The `$V3.76`` update is now available for your device.  Go get it!  You'll need to install it before you can play online. the script need to be updated or another thing to do

**Comment by CapciGithub** [comment]
> Message: `` 4UPDATE REQUIRED!`` : The ``$V3.76`` update is now available for your device. Go get it! You'll need to install it before you can play online. the script need to be updated or another thing to do

Go to Editor on Google Cloud Shell and delete the CID-Creator folder with everything inside then do what you did before. Repeat all the steps from zero and you will have updated version.
