### ISSUE TITLE
can't create account

### ISSUE THREAD

**Issue by ase24** [CapciGithub/Growtopia-CID-Creator#9]
always stuck at "Connected to server, creating account!"

![image](https://user-images.githubusercontent.com/95928532/145602644-b805edd2-5cca-49e0-b9a6-0e4772c2d6d5.png)

**Comment by vMandQv** [comment]
Hello I'm Sahyui#1067 

bot1 = makeBot(user1, pass1,"213.179.209.168", 17200, vers, wn);

Change 17200 to 17201

**Comment by ase24** [comment]
still can not

**Comment by vMandQv** [comment]
Contact with me on discord. Sahyui#1067

**Comment by CapciGithub** [comment]
> always stuck at "Connected to server, creating account!"
> 
> ![image](https://user-images.githubusercontent.com/95928532/145602644-b805edd2-5cca-49e0-b9a6-0e4772c2d6d5.png)

First of all, make sure your Username is not that long. Second of all make sure at least there is 1 capital letters 1 symbol and 1 number iin your password for example: Password1@ then make sure to put at least random email into 
//Customing Gmail ( At least put a random gmail. Dont add @gmail.com )
string Gmail_acc = "testgmail";

change testgmail with anything random and make sure its not long keep it short and dont put @gmail.com into end.

If still somehow doesnt works, open the editor and delete the Growtopia-CID-Creator folder and do everything from step 1.
